=== fabiodelabruna/materiais-cursos/Curso Sequencial em desenvolvimento de soluções Java para Web - UNISUL/5 - Java para Web/Exercicios/AulaXML/arquivos/Empresa.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Empresa" type="empresa" />

	<xs:complexType name="empresa">
		<xs:sequence>
			<xs:element name="Nome_Empresa" type="xs:string" />
			<xs:element name="Cnpj" type="xs:string" />
			<xs:element name="Endereco" type="endereco" />
			<xs:element name="Setor" type="setor" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="endereco">
		<xs:sequence>
			<xs:element name="Logradouro" type="xs:string" />
			<xs:element name="Numero" type="xs:integer" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="setor">
		<xs:sequence>
			<xs:element name="Funcionario" type="funcionario"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="funcionario">
		<xs:sequence>
			<xs:element name="Nome_Funcionario" type="xs:string" />
			<xs:element name="Idade" type="xs:integer" />
			"
		</xs:sequence>
	</xs:complexType>


</xs:schema>

=== fabiodelabruna/materiais-cursos/Curso Sequencial em desenvolvimento de soluções Java para Web - UNISUL/5 - Java para Web/Exercicios/AulaXML/arquivos/Empresa.xml
<Empresa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="Empresa.xsd">
	<Nome_Empresa>
		NomeTesteDeEmpresa
	</Nome_Empresa>
	<Cnpj>
		1234567890
	</Cnpj>
	<Endereco>
		<Logradouro>
			AvTeste
		</Logradouro>
		<Numero>
			123
		</Numero>
	</Endereco>
	<Setor>
		<Funcionario>
			<Nome_Funcionario>
				FuncionarioTeste
			</Nome_Funcionario>
			<Idade>
				19
			</Idade>
		</Funcionario>
	</Setor>
	

</Empresa>
